# Generated by Django 2.1.5 on 2019-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='RFID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
