# Generated by Django 2.1.5 on 2019-11-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191103_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='finger',
        ),
    ]
